#########################
POST http://127.0.0.1:8000/sport/question/1/
Content-Type: application/json
Accept: application/json

{
  "age": 12
}
#########################
POST http://127.0.0.1:8000/sport/question/12/
Content-Type: application/json
Accept: application/json

{
  "category":12,
  "score":12
}
