###############
POST http://127.0.0.1:8000/
Content-Type: application/json
Accept: application/json

{
  
}

#########################3
GET http://127.0.0.1:8000/sport/
Content-Type: application/json
Accept: application/json
