# Generated by Django 5.2.1 on 2025-06-02 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن سوال')),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('category', models.CharField(max_length=50, verbose_name='دسته بندی')),
                ('type', models.CharField(choices=[('text', 'متنی'), ('choice', 'چند گزینه ای')], default='choice', max_length=10, verbose_name='نوع سوال')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SportFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name-sport')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'name-sport',
                'verbose_name_plural': 'name-sports',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='متن پاسخ')),
                ('points', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('age', models.IntegerField(default=0, verbose_name='age')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ\u200cها',
                'unique_together': {('question', 'text')},
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='کلید سشن')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='پاسخ متنی')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت پاسخ')),
                ('chosen_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.answer', verbose_name='پاسخ انتخاب شده')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ کاربر',
                'verbose_name_plural': 'پاسخ\u200cهای کاربران',
                'unique_together': {('session_key', 'question')},
            },
        ),
    ]
