# Generated by Django 5.2.1 on 2025-06-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_anonymoususerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
