# Generated by Django 5.2.1 on 2025-06-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_userresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategoryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='کلید سشن')),
                ('category', models.CharField(max_length=50, verbose_name='دسته بندی سوال')),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز کسب شده در این دسته بندی')),
            ],
            options={
                'verbose_name': 'امتیاز دسته بندی کاربر',
                'verbose_name_plural': 'امتیازات دسته بندی کاربران',
                'unique_together': {('session_key', 'category')},
            },
        ),
    ]
