# Generated by Django 5.2.1 on 2025-06-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_usercategoryscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategoryscore',
            name='score',
            field=models.FloatField(default=0, verbose_name='امتیاز کسب شده در این دسته بندی'),
        ),
    ]
