# Generated by Django 5.2.1 on 2025-06-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_usercategoryscore_session_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
    ]
