# Generated by Django 5.2.1 on 2025-07-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_answer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=200)),
                ('result', models.TextField(max_length=250)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='anonymoususerprofile',
            name='full_name',
            field=models.CharField(default='Anonymous User', max_length=200),
        ),
    ]
