# Generated by Django 5.2.1 on 2025-07-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_resultuser_anonymoususerprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
